server:
  port: 8088
spring:
  cloud:
    stream:
      bindings:
        testout:
          destination: receiver
        testin:
          destination: receiver1
        testinout:
          destination: receiver2
        checktopic:
          destination: checkTp
        bpsOut:
          destination: BP.DATA.PE.GM.DEMO.INT.TOPIC
        bpsIn:
          destination: BP.DATA.LN.OUTPUT.GM.DEMO.INT.TOPIC
